# Generated by Django 5.1.7 on 2025-04-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_sociallink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='about',
            name='linkedin_link',
        ),
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(max_length=300),
        ),
    ]
